# Generated by Django 4.2.8 on 2026-05-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('prenatal', 'Prenatal Care'), ('child_health', 'Child Health'), ('general', 'General Health Concern'), ('family_planning', 'Family Planning'), ('follow_up', 'Follow-up Checkup'), ('immunization', 'Immunization'), ('nutrition', 'Nutrition Counseling'), ('dental', 'Dental Checkup'), ('mental_health', 'Mental Health')], max_length=20)),
                ('consultation_method', models.CharField(choices=[('video_call', 'Online Video Call'), ('voice_call', 'Online Voice Call'), ('chat', 'Chat Consultation'), ('in_person', 'In-Person Visit')], default='video_call', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('reason_for_visit', models.TextField(help_text='Brief description of symptoms or reason for consultation')),
                ('symptoms', models.TextField(blank=True, help_text='List of symptoms (if applicable)', null=True)),
                ('consultation_notes', models.TextField(blank=True, help_text='Notes from the health worker after consultation', null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations, prescriptions, or follow-up instructions', null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('call_room_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('health_worker', models.ForeignKey(blank=True, limit_choices_to={'role': 'health_worker'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_appointments', to=settings.AUTH_USER_MODEL)),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment')),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(max_length=20)),
                ('consultation_method', models.CharField(max_length=20)),
                ('consultation_date', models.DateField()),
                ('chief_complaint', models.TextField()),
                ('symptoms_observed', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_provided', models.TextField(blank=True, null=True)),
                ('medications_prescribed', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='consultation_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_record', to='appointments.appointment')),
                ('health_worker', models.ForeignKey(limit_choices_to={'role': 'health_worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='provided_consultations', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation Record',
                'verbose_name_plural': 'Consultation Records',
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('health_worker', models.ForeignKey(limit_choices_to={'role': 'health_worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('health_worker', 'date', 'start_time')},
            },
        ),
    ]
