# Generated by Django 4.2.30 on 2026-05-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='custom_consultation_type',
            field=models.CharField(blank=True, help_text="Custom consultation type when 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('prenatal', 'Prenatal Care'), ('child_health', 'Child Health'), ('general', 'General Health Concern'), ('family_planning', 'Family Planning'), ('follow_up', 'Follow-up Checkup'), ('immunization', 'Immunization'), ('nutrition', 'Nutrition Counseling'), ('dental', 'Dental Checkup'), ('mental_health', 'Mental Health'), ('other', 'Other')], max_length=20),
        ),
    ]
