# Generated by Django 4.2.8 on 2026-05-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('video', 'Video Call'), ('voice', 'Voice Call')], max_length=10)),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('resident_joined', models.BooleanField(default=False)),
                ('health_worker_joined', models.BooleanField(default=False)),
                ('resident_left_at', models.DateTimeField(blank=True, null=True)),
                ('health_worker_left_at', models.DateTimeField(blank=True, null=True)),
                ('call_quality_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 rating of call quality', null=True)),
                ('technical_issues', models.TextField(blank=True, help_text='Any technical issues encountered during the call', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the consultation', null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_consultation', to='appointments.appointment')),
                ('health_worker', models.ForeignKey(limit_choices_to={'role': 'health_worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_consultations', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Consultation',
                'verbose_name_plural': 'Online Consultations',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_satisfaction', models.PositiveSmallIntegerField(help_text='Overall satisfaction with the consultation (1-5)')),
                ('doctor_competence', models.PositiveSmallIntegerField(blank=True, help_text="Health worker's competence (1-5)", null=True)),
                ('communication_clarity', models.PositiveSmallIntegerField(blank=True, help_text='Clarity of communication (1-5)', null=True)),
                ('technical_quality', models.PositiveSmallIntegerField(blank=True, help_text='Technical quality of the call (1-5)', null=True)),
                ('would_recommend', models.BooleanField(help_text='Would you recommend this service to others?', null=True)),
                ('positive_feedback', models.TextField(blank=True, help_text='What went well?', null=True)),
                ('improvement_suggestions', models.TextField(blank=True, help_text='What could be improved?', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='consultations.onlineconsultation')),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation Feedback',
                'verbose_name_plural': 'Consultation Feedback',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('initiated', 'Call Initiated'), ('joined', 'Participant Joined'), ('left', 'Participant Left'), ('ended', 'Call Ended'), ('connection_lost', 'Connection Lost'), ('reconnected', 'Reconnected'), ('error', 'Error')], max_length=20)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='consultations.onlineconsultation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
